---
name: Guillem Salazar
address: "ETH Zürich, Switzerland"
profilepic: "../images/profile.png"
www: guillemsalazar.github.io
email: "guillems@ethz.ch"
github: GuillemSalazar
orcid: 0000-0002-9786-1493
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 007599
aboutme: "I use computational tools to understand how marine microbial communities are shaped and respond to environmental change."
docname: cv
output: 
  vitae::moderncv:
    theme: casual
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(vitae)
library(tinytex)
library(tidyverse)
library(xlsx)

cv_info<-read.xlsx("cv_input_data/cv_info.xlsx",sheetIndex = 1)
cv_info<-cv_info %>%
  mutate_if(is.factor,as.character) %>%
  arrange(end_year) %>%
  mutate(when=end_year)
```

# Academic Information

```{r ACADEMIC_INFO}
cv_info %>%
  filter(section=="academic") %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where
  )
```

# Grants and Contracts

```{r GRANT_CONTRACT}
cv_info %>%
  filter(section=="grant_contract") %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where
  )
```

# Courses

```{r COURSES}
cv_info %>%
  filter(section=="course") %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where
  )
```

# Teaching

```{r TEACHING}
cv_info %>%
  filter(section=="teaching") %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where
  )
```

\newpage
# Oral presentations in conferences

```{r ORAL}
cv_info %>%
  filter(section=="oral") %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where
  )
```

# Posters in conferences

```{r POSTER}
cv_info %>%
  filter(section=="poster") %>%
  detailed_entries(
    what = what,
    when = when,
    with = with,
    where = where
  )
```
\newpage
# Publications

```{r PUBLICATIONS}
pbs_df<-readRDS("cv_input_data/pubs_data.rds")
pbs_df %>%
  mutate(author_string=gsub("\\*","",author_string)) %>%
  mutate(journal_string=gsub("\\*","",journal_string)) %>%
  detailed_entries(
    what = title_string,
    when = year,
    with = author_string,
    where = journal_string
  )

```

